version: 2
updates:
  - package-ecosystem: npm
    directory: /TypePulse
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /TypePulse
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
